mcp:
  servers:
    rag:
      url: "wss://rag.svc.cluster.local:443"
      timeout_ms: 800
      local_url: "ws://localhost:8081"
      description: "RAG search with OpenSearch and Bedrock Knowledge Bases"
      tools:
        - name: "rag.search"
          description: "Semantic and hybrid search across ingested documents"
          parameters:
            query: "Search query string"
            filters: "Optional filters (dealId, geo, asset, after)"
            topK: "Number of results to return (default: 5)"

    parser:
      url: "wss://parser.svc.cluster.local:443"
      timeout_ms: 30000
      local_url: "ws://localhost:8082"
      description: "Document parsing with AWS Textract"
      tools:
        - name: "parser.extract"
          description: "Extract structured data from PDF/image documents"
          parameters:
            s3Uri: "S3 URI of document to parse"
            dealId: "Deal ID for context and storage"

    findb:
      url: "wss://findb.svc.cluster.local:443"
      timeout_ms: 200
      local_url: "ws://localhost:8083"
      description: "Financial database queries with ABAC filtering"
      tools:
        - name: "findb.query"
          description: "Query deal metrics and financial data"
          parameters:
            dealId: "Specific deal ID to query"
            filters: "Optional filters for bulk queries"

    web:
      url: "wss://web.svc.cluster.local:443"
      timeout_ms: 1500
      local_url: "ws://localhost:8084"
      description: "Web research with allowlisted domains"
      tools:
        - name: "web.search"
          description: "Search allowlisted web sources with credibility scoring"
          parameters:
            queries: "Array of search query strings"
            allowlistGroup: "Allowlist group for domain filtering"

    calc:
      url: "wss://calc.svc.cluster.local:443"
      timeout_ms: 150
      local_url: "ws://localhost:8085"
      description: "Financial calculations with provenance tracking"
      tools:
        - name: "calc.compute"
          description: "Perform financial calculations (IRR, NPV, DSCR)"
          parameters:
            formula: "Calculation type (irr, npv, dscr, etc.)"
            inputs: "Calculation inputs as key-value pairs"

    report:
      url: "wss://report.svc.cluster.local:443"
      timeout_ms: 1500
      local_url: "ws://localhost:8086"
      description: "DOCX report generation with S3 storage"
      tools:
        - name: "report.create"
          description: "Generate formatted DOCX report from analysis"
          parameters:
            structuredAnalysis: "Analysis data conforming to schema"
            templateType: "Report template type (default: standard)"

  connection:
    retry_attempts: 3
    retry_delay_ms: 1000
    heartbeat_interval_ms: 30000

  security:
    validate_certificates: true
    allowed_origins: ["https://mavik-ai.com", "http://localhost:3000"]
