mcp:
  servers:
    rag:
      name: "RAG Search Service"
      url: ${MCP_RAG_URL}
      url_local: ${MCP_RAG_URL_LOCAL}
      timeout_ms: 800
      retry_attempts: 2
      description: "Hybrid vector + BM25 search with OpenSearch Serverless and Bedrock Knowledge Bases"
      capabilities:
        - semantic_search
        - filtered_search
        - citation_retrieval
        - confidence_scoring
      tools:
        - name: "rag.search"
          description: "Search documents using hybrid ANN + BM25 approach"
          timeout_ms: 800

    parser:
      name: "Document Parser Service"  
      url: ${MCP_PARSER_URL}
      url_local: ${MCP_PARSER_URL_LOCAL}
      timeout_ms: 30000
      retry_attempts: 1
      description: "Textract-based document processing with table extraction and confidence scoring"
      capabilities:
        - document_parsing
        - table_extraction
        - text_normalization
        - confidence_scoring
      tools:
        - name: "parser.extract"
          description: "Extract tables and text from offering memorandums"
          timeout_ms: 30000

    findb:
      name: "Financial Database Service"
      url: ${MCP_FINDB_URL}
      url_local: ${MCP_FINDB_URL_LOCAL}
      timeout_ms: 200
      retry_attempts: 3
      description: "Aurora PostgreSQL queries with RBAC and MNPI filtering"
      capabilities:
        - financial_metrics
        - deal_queries
        - tenant_data
        - abac_filtering
      tools:
        - name: "findb.query"
          description: "Query financial metrics and deal data with ABAC enforcement"
          timeout_ms: 200

    web:
      name: "Web Research Service"
      url: ${MCP_WEB_URL}
      url_local: ${MCP_WEB_URL_LOCAL}
      timeout_ms: 1500
      retry_attempts: 2
      description: "Allowlisted web scraper with DynamoDB caching and credibility scoring"
      capabilities:
        - web_scraping
        - domain_allowlist
        - content_caching
        - credibility_scoring
      tools:
        - name: "web.search"
          description: "Search allowlisted websites with caching"
          timeout_ms: 1500

    calc:
      name: "Financial Calculator Service"
      url: ${MCP_CALC_URL}
      url_local: ${MCP_CALC_URL_LOCAL}
      timeout_ms: 150
      retry_attempts: 1
      description: "Deterministic financial calculations with provenance tracking"
      capabilities:
        - irr_calculation
        - npv_calculation
        - dscr_calculation
        - debt_yield_calculation
      tools:
        - name: "calc.compute"
          description: "Compute financial metrics with explanation"
          timeout_ms: 150

    report:
      name: "Report Generation Service"
      url: ${MCP_REPORT_URL}
      url_local: "http://localhost:8086"  # Lambda local for testing
      timeout_ms: 1500
      retry_attempts: 1
      description: "DOCX report generation with S3 storage and presigned URLs"
      capabilities:
        - docx_generation
        - s3_storage
        - presigned_urls
        - template_rendering
      tools:
        - name: "report.create"
          description: "Generate DOCX report from structured analysis"
          timeout_ms: 1500

  # Connection settings
  connection:
    max_connections: 10
    connection_timeout_ms: 5000
    keepalive_interval_ms: 30000
    max_message_size: 1048576  # 1MB
    
  # Health check configuration
  health_check:
    enabled: true
    interval_ms: 60000
    timeout_ms: 5000
    unhealthy_threshold: 3
    healthy_threshold: 2

  # Monitoring and observability
  monitoring:
    metrics_enabled: true
    tracing_enabled: true
    log_requests: true
    log_responses: false  # May contain sensitive data
    
  # Error handling
  error_handling:
    max_retries: 3
    backoff_multiplier: 2.0
    max_backoff_ms: 10000
    circuit_breaker_enabled: true
    circuit_breaker_threshold: 10
    circuit_breaker_timeout_ms: 60000
