[tool.poetry]
name = "mavik-aws-clients"
version = "0.1.0"
description = "AWS service clients for Mavik AI services"
authors = ["Mavik Capital <engineering@mavikcapital.com>"]
packages = [{include = "mavik_aws_clients", from = "."}]

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.34.0"
pydantic = "^2.5.0"
tenacity = "^8.2.0"
opensearch-py = "^2.3.0"
aioboto3 = "^13.0.0"
asyncpg = "^0.29.0"
requests-aws4auth = "^1.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"