[tool.poetry]
name = "mavik-config"
version = "0.1.0"
description = "Configuration management for Mavik AI services"
authors = ["Mavik Capital <engineering@mavikcapital.com>"]
packages = [{include = "mavik_config", from = "."}]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.5.0"
pydantic-settings = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"