name: PR1 Checks

on:
  pull_request:
    branches: [ "**" ]

jobs:
  pr1-gates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.3'

      - name: Install dependencies
        run: |
          poetry env use 3.11
          poetry install --no-interaction

      - name: Ruff (scoped)
        run: |
          poetry run ruff check packages/common tests/common
          poetry run ruff check apps/orchestrator tests/orchestrator

      - name: MyPy (scoped)
        run: |
          poetry run mypy packages/common
          poetry run mypy apps/orchestrator

      - name: PyTest (scoped)
        run: |
          poetry run pytest -q tests/common -q
          poetry run pytest -q tests/orchestrator -q